### ISSUE TITLE
py.3.10.0 install error

### ISSUE THREAD

**Issue by ghost** [ApeWorX/py-solc-x#130]
### Environment information

* `py-solc-x` Version: last 
* `solc` Version: x.x.x
* Python Version: 3.10
* OS: osx/linux/win

### What was wrong?
i can import the library /w python v.3.10.0 check the photo
![image](https://user-images.githubusercontent.com/89277831/140236986-f4e1ea0c-52c7-414d-9ca9-cb3aadc9c006.png)

Please include information like:

* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you know how the bug could be fixed.

**Comment by TekyaygilFethi** [comment]
Could you please look to where it installed via executing `pip3 show py-solc-x` command? In my case I was using Python 3.10 but package has been installed under Python 3.8 which I had to change interpreter to Python 3.8 in Visual Studio Code to get things done.

**Comment by TekyaygilFethi** [comment]
Could you please look to where it installed via executing pip3 show `py-solc-x` and `pip3 show solc` commands? In my case I was using Python 3.10 but package has been installed under Python 3.8 which I had to change interpreter to Python 3.8 in Visual Studio Code to get things done.

**Comment by antazoey** [comment]
seems like an env var issue! The package works on 3.10.0 now, as verified by tests
