### ISSUE TITLE
Warning msg on import

### ISSUE THREAD

**Issue by mrx23dot** [ApeWorX/py-solc-x#141]
### Environment information
py-solc-x==1.1.1
win10
Python 3.7.0

### What was wrong?
Doing a simple import prints msg on console, this is highly unusual.

```
>>> import solcx
INFO: Could not find files for the given pattern(s).
```

### How can it be fixed?
Remove print on import.

**Comment by antazoey** [comment]
this log stmt is no longer found anywhere in the package so im going to close
